/*=============================================================
  Teardown - Cleanup Script
  Drops all objects created by the pipeline
=============================================================*/

USE DATABASE INSIGHT_PIPELINE;
USE SCHEMA CRYPTO;

-- Suspend tasks and alerts first
ALTER TASK IF EXISTS INGEST_CRYPTO_TASK SUSPEND;
ALTER TASK IF EXISTS SIMULATE_CRYPTO_TASK SUSPEND;
ALTER ALERT IF EXISTS CRYPTO_ANOMALY_ALERT SUSPEND;

-- Drop alerts
DROP ALERT IF EXISTS CRYPTO_ANOMALY_ALERT;

-- Drop tasks
DROP TASK IF EXISTS INGEST_CRYPTO_TASK;
DROP TASK IF EXISTS SIMULATE_CRYPTO_TASK;

-- Drop dynamic tables
DROP DYNAMIC TABLE IF EXISTS CRYPTO_ANOMALIES;
DROP DYNAMIC TABLE IF EXISTS CRYPTO_5MIN_AGG;

-- Drop stream
DROP STREAM IF EXISTS CRYPTO_TICKS_STREAM;

-- Drop procedures
DROP PROCEDURE IF EXISTS GENERATE_CRYPTO_TICKS(INT);
DROP PROCEDURE IF EXISTS INGEST_CRYPTO_FROM_API();

-- Drop tables
DROP TABLE IF EXISTS RAW_CRYPTO_TICKS;

-- Drop integrations
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS COINGECKO_ACCESS_INTEGRATION;
DROP NETWORK RULE IF EXISTS COINGECKO_NETWORK_RULE;

-- Drop schema and database
DROP SCHEMA IF EXISTS INSIGHT_PIPELINE.CRYPTO;
DROP DATABASE IF EXISTS INSIGHT_PIPELINE;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS INSIGHT_WH;

-- Drop role (optional)
-- USE ROLE SECURITYADMIN;
-- DROP ROLE IF EXISTS INSIGHT_PIPELINE_ROLE;
