/*=============================================================
  10 - Grants (Optional)
  Role-based access for the pipeline objects
=============================================================*/

USE ROLE SECURITYADMIN;

-- Create a role for the pipeline
CREATE ROLE IF NOT EXISTS INSIGHT_PIPELINE_ROLE;

-- Grant database and schema access
GRANT USAGE ON DATABASE INSIGHT_PIPELINE TO ROLE INSIGHT_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA INSIGHT_PIPELINE.CRYPTO TO ROLE INSIGHT_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE INSIGHT_WH TO ROLE INSIGHT_PIPELINE_ROLE;

-- Grant table/view access
GRANT SELECT ON ALL TABLES IN SCHEMA INSIGHT_PIPELINE.CRYPTO TO ROLE INSIGHT_PIPELINE_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA INSIGHT_PIPELINE.CRYPTO TO ROLE INSIGHT_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INSIGHT_PIPELINE.CRYPTO TO ROLE INSIGHT_PIPELINE_ROLE;

-- Grant execute on procedures
GRANT USAGE ON PROCEDURE INSIGHT_PIPELINE.CRYPTO.GENERATE_CRYPTO_TICKS(INT) TO ROLE INSIGHT_PIPELINE_ROLE;
GRANT USAGE ON PROCEDURE INSIGHT_PIPELINE.CRYPTO.INGEST_CRYPTO_FROM_API() TO ROLE INSIGHT_PIPELINE_ROLE;

-- Assign role to current user (update as needed)
-- GRANT ROLE INSIGHT_PIPELINE_ROLE TO USER <your_username>;
